name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker image server
        run: |
          cd server
          docker build --tag ghcr.io/$GITHUB_ACTOR/rtmp-server:latest --tag ghcr.io/$GITHUB_ACTOR/rtmp-server:$(echo $GITHUB_SHA | head -c7) .
      - name: docker push server
        run: |
          cd server
          docker push ghcr.io/$GITHUB_ACTOR/rtmp-server:latest
          docker push ghcr.io/$GITHUB_ACTOR/rtmp-server:$(echo $GITHUB_SHA | head -c7)
      - name: docker image sender
        run: |
          cd sender
          docker build --tag ghcr.io/$GITHUB_ACTOR/rtmp-sender:latest --tag ghcr.io/$GITHUB_ACTOR/rtmp-sender:$(echo $GITHUB_SHA | head -c7) .
      - name: docker push semder
        run: |
          cd sender
          docker push ghcr.io/$GITHUB_ACTOR/rtmp-sender:latest
          docker push ghcr.io/$GITHUB_ACTOR/rtmp-sender:$(echo $GITHUB_SHA | head -c7)
